### PR TITLE
little fixes

### PR DESCRIPTION
**Pull request by npignier**
Little fixes after seeing the translations live on the UI

note : the label key for : "Please upload a picture for the group" is missing in the files

### CODE REVIEW

**Comment by npignier** [comment]
A problem with the translation of "You follow her and she follows you".
French label is wrong with he/she/... : 
`"Vous suivez SA et elle vous suit.", `
It should be 
`"Vous LA suivez et elle vous suit"`
So maybe the best way is to translate the whole sentence, not parts of the sentence.

**Comment by npignier** [comment]
After that the french language will be ready for a public beta test :-)

**Comment by npignier** [comment]
Missing this label at the botteom of the page in the translations :
image

**Comment by davidtinker** [comment]
Would love to release fr but we (tx!) still need to do a bunch of work to make things fit. The subjective wellness labels 'Sore', 'Fat', 'Str' and 'Mot' are a problem as is "Up" (Dénivelé). There are other examples. I am going to try make space generally (e.g. on the settings page).

Screen Shot 2021-09-01 at 20 05 38

**Comment by davidtinker** [comment]
Here is another:

Screen Shot 2021-09-01 at 20 32 27

**Comment by davidtinker** [comment]
Oooh this list is getting longer .. :(

Screen Shot 2021-09-01 at 20 43 20

**Pull request merged**
